# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "%s"
og_image: /img/og_clinton.png
author: David Clinton
favicon: /img/favicon.png
description: Software Engineer
port: 8083


origin: https://daveclintonn.cc
og: /img/og.jpg


navigation:
  header: 
    - DC: /
    - Bookmarks: /bookmarks/
    - About: /about

  footer:
    - © David Clinton: /

    - image: /img/twitter.svg
      url: //x.com/daveclintonn
      alt: Twitter (X) profile
      size: 22 x 22

    - image: /img/github.svg
      url: //github.com/daveclinton 
      alt: Github Projects
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/clintondavid46/
      alt: LinkedIn profile
      size: 22 x 22
